name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository-ni klonlama
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Docker image build etmə
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: "srthealikk"
          password: "p4UYX8R%!hAP/i5"

      - name: Build Docker image
        run: |
          docker build -t srthealikk/frontend-project:latest .

      # 3. Docker Hub-a push etmə
      - name: Push Docker image to Docker Hub
        run: |
          docker push srthealikk/frontend-project:latest

      # 4. Kubernetes deployment-ı yeniləmə
      - name: Checkout master branch
        uses: actions/checkout@v3
        with:
          ref: master  # Ensure this checks out the master branch

      - name: kubectl - Google GKE cluster
        uses: ameydev/gke-kubectl-action@master
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
          ZONE_NAME: ${{ secrets.GKE_ZONE_NAME }}
          APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        run: |
          kubectl set image deployment/frontend-deployment frontend=srthealikk/frontend:latest
          kubectl rollout restart deployment/frontend-deployment
