name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository-ni klonlama
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Docker image build etmə
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: "srthealikk"
          password: "p4UYX8R%!hAP/i5"

      - name: Build Docker image
        run: |
          docker build -t srthealikk/frontend-project:latest .

      # 3. Docker Hub-a push etmə
      - name: Push Docker image to Docker Hub
        run: |
          docker push srthealikk/frontend-project:latest

  Deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository (for kubectl deployment context)
      - uses: actions/checkout@v3
        with:
          ref: main

      # kubectl - Google Cloud GKE cluster
      - name: kubectl - Google Cloud GKE cluster
        uses: ameydev/gke-kubectl-action@master
        with:
          args: |
            kubectl apply -f k8s/front-deploy.yaml
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
          CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
          ZONE_NAME: ${{ secrets.GKE_ZONE_NAME }}



















