name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  Deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate Docker tag
        id: generate_tag
        run: echo "tag=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV


      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-project:${{ env.tag }} .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend-project:${{ env.tag }}

            - uses: actions/checkout@v3
        with:
          ref: main


      - name: Update Kubernetes Deployment file
        run: |
          sed -i "s|^\([[:space:]]*image: \).*|\1${{ secrets.DOCKER_USERNAME }}/frontend-project:${{ env.tag }}|" k8s/front-deploy.yaml


      - name: kubectl - Google Cloud GKE cluster
        uses: ameydev/gke-kubectl-action@master
        with:
          args: apply -f k8s/front-deploy.yaml
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
          CLUSTER_NAME: ${{ secrets.GKE_CLUSTER_NAME }}
          ZONE_NAME: ${{ secrets.GKE_ZONE_NAME }}











