name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository-ni klonlama
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Docker image build etmə
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: "srthealikk"
          password: "p4UYX8R%!hAP/i5"

      - name: Build Docker image
        run: |
          docker build -t srthealikk/frontend-project:latest .

      # 3. Docker Hub-a push etmə
      - name: Push Docker image to Docker Hub
        run: |
          docker push srthealikk/frontend-project:latest

      # 4. Kubernetes deployment-ı yeniləmə
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Update Kubernetes Deployment
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          kubectl set image deployment/frontend-deployment frontend=srthealikk/frontend:latest
          kubectl rollout restart deployment/frontend-deployment


